CREATE TABLE CLIENTES (
    CLIENTE_ID SERIAL NOT NULL,
    CLIENTE_NOMBRE VARCHAR (25),
    CLIENTE_APELLIDO VARCHAR (25),
    CLIENTE_GENERO VARCHAR(50),
    CLIENTE_SITUACION INTEGER DEFAULT 1,
    PRIMARY KEY (CLIENTE_ID)
)